version: "3"
services:
  mongo-db:
    image: mongo:4
    container_name: "mongo-db"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=moviesDb
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
    networks:
      - default
  movies-app:
    depends_on:
      - mongo-db
    container_name: "movies-app"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/moviesDb
      - MOVIESDB_POPULATEBYINITDATA=true
    links:
      - mongo-db:mongo
    build: .
    ports:
      - "8080:8080"
    networks:
      - default